


shinyUI(dashboardPage(
  dashboardHeader(title = "U.S. Cancer Diagnoses: 1999 - 2015", titleWidth = 350),
  dashboardSidebar(
    sidebarUserPanel("Eric Meyers", image = './robot-icon.png'),
    sidebarMenu(
      menuItem("Home", tabName = "home", icon = icon("home")),
      menuItem("Map", tabName = "map", icon = icon("globe-americas")),
      menuItem("Age", tabName = "age", icon = icon("clock")),
      menuItem("Race Counts", tabName = "race", icon = icon("user-friends")),
      menuItem("Race Distribution", tabName = "race2", icon = icon("users")),
      menuItem("State", tabName = "state", icon = icon("flag")),
      menuItem("Gender", tabName = "gender", icon = icon("venus-mars")),
      menuItem("Data", tabName = "data", icon = icon("database")),
      menuItem("Age/Race/Gender Mosaic", tabName = "mosaic", icon = icon("th"))
      )),
  dashboardBody(
    tabItems(
      tabItem(tabName = "home",
              fluidRow(tags$div(
                tags$h1(tags$b("U.S. Cancer Diagnoses Research Application (1999 - 2015)")), br(),
                tags$h2(tags$b(tags$em("Contents"))),
                tags$h3("+ U.S. Map 2015: Diagnoses by State"),
                tags$h3("+ Diagnoses by Age"),
                tags$h3("+ Diagnoses by Race"),
                tags$h3("+ Distribution by Race"),
                tags$h3("+ Diagnoses by State"),
                tags$h3("+ Diagnoses by Gender"),
                tags$h3("+ Data Tables"),
                tags$h3("+ Age/Race/Gender Mosaic"),
                tags$h4("Source: All data comprised herein is provided as is by the Center for Disease Control (CDC), for more information: ",
                        tags$a(href='https://wonder.cdc.gov/cancer-v2015.html', "Click here!"))
                        ))),
      tabItem(tabName = "map",
              fluidRow("U.S. Cancer Diagnoses: 2015", style = "font-size:35px",
                       br(),
                       box(htmlOutput("map"), width = 1100, height = 500))),
      tabItem(tabName = "age",
              fluidRow(column(6,
                              selectizeInput(inputId = "Race1",
                                             label = "Race",
                                             choices = unique(cancer$Race),
                                             selected = "White"),
                              selectizeInput(inputId = "States1",
                                             label = "State",
                                             choices = unique(cancer$States),
                                             selected = "California")),
                       column(6,
                              selectizeInput(inputId = "Sex1",
                                             label = "Gender",
                                             choices = unique(cancer$Sex)),
                              selectizeInput(inputId = "Year1",
                                             label = "Year",
                                             choices = unique(cancer$Year),
                                             selected = 2015))
              ),
              plotOutput("CountByAge")),
      tabItem(tabName = "race",
              fluidRow(column(6,
                              selectizeInput(inputId = "States2",
                                             label = "State",
                                             choices = unique(cancer$States),
                                             selected = "California"),
                              selectizeInput(inputId = "Age.Groups.Code2",
                                             label = "Age Group",
                                             choices = unique(cancer$Age.Groups.Code),
                                             selected = 65)),
                       column(6,
                              selectizeInput(inputId = "Sex2",
                                             label = "Gender",
                                             choices = unique(cancer$Sex)),
                              selectizeInput(inputId = "Year2",
                                             label = "Year",
                                             choices = unique(cancer$Year),
                                             selected = 2015))
              ),
              plotOutput("CountByRace")),
      tabItem(tabName = "race2",
              fluidRow(column(6,
                              selectizeInput(inputId = "States3",
                                             label = "State",
                                             choices = unique(cancer$States),
                                             selected = "California"),
                              selectizeInput(inputId = "Year3",
                                             label = "Year",
                                             choices = unique(cancer$Year),
                                             selected = 2015)),
                       column(6,
                              selectizeInput(inputId = "Sex3",
                                             label = "Gender",
                                             choices = unique(cancer$Sex)))
              ),
              plotOutput("DistByRace")),
      tabItem(tabName = "state",
              fluidRow(column(6,
                              selectizeInput(inputId = "Race4",
                                             label = "Race",
                                             choices = unique(cancer$Race),
                                             selected = "White"),
                              selectizeInput(inputId = "Age.Groups.Code4",
                                             label = "Age Group",
                                             choices = unique(cancer$Age.Groups.Code),
                                             selected = 65)),
                       column(6,
                              selectizeInput(inputId = "Sex4",
                                             label = "Gender",
                                             choices = unique(cancer$Sex)),
                              selectizeInput(inputId = "Year4",
                                             label = "Year",
                                             choices = unique(cancer$Year),
                                             selected = 2015))
                              ),
              plotOutput("CountByState")),
      tabItem(tabName = "gender",
              fluidRow(column(6,
                              selectizeInput(inputId = "Race5",
                                             label = "Race",
                                             choices = unique(cancer$Race),
                                             selected = "White"),
                              selectizeInput(inputId = "Age.Groups.Code5",
                                             label = "Age Group",
                                             choices = unique(cancer$Age.Groups.Code),
                                             selected = 65)),
                       column(6,
                              selectizeInput(inputId = "States5",
                                             label = "State",
                                             choices = unique(cancer$States),
                                             selected = "California"),
                              selectizeInput(inputId = "Year5",
                                             label = "Year",
                                             choices = unique(cancer$Year),
                                             selected = 2015))
              ),
              plotOutput("CountByGender")),
      tabItem(tabName = "data",
              fluidRow(column(4,
                selectizeInput(inputId = "Race6",
                               label = "Race",
                               choices = unique(cancer$Race),
                               selected = "White"),
                selectizeInput(inputId = "States6",
                               label = "State",
                               choices = unique(cancer$States),
                               selected = "California")),
                column(4,
                selectizeInput(inputId = "Sex6",
                               label = "Gender",
                               choices = unique(cancer$Sex)),
                selectizeInput(inputId = "Year6",
                               label = "Year",
                               choices = unique(cancer$Year),
                               selected = 2015)),
                column(4,
                selectizeInput(inputId = "Age.Groups.Code6",
                               label = "Age Group",
                               choices = unique(cancer$Age.Groups.Code),
                               selected = 65))
              ),
              fluidRow(box(DT::dataTableOutput("raw_table"),
                           width = 12))),
      tabItem(tabName = "mosaic", plotOutput("mosaic1"))
      )
    
        )
  )
)